name: deno-linter

on: push

jobs:
  deno-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup deno-linter
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: deno formatter
        run: deno fmt

      - name: deno linter
        run: deno lint --unstable

      - name: deno tester
        run: deno test
  
