name: deno-linter

on: push

jobs:
  deno-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deno-linter
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: |
          deno --version
          deno run https://deno.land/std/examples/welcome.ts
          deno install --allow-read -n deno_cat https://deno.land/std/examples/cat.ts
          deno_cat ./README.md
