name: deno-linter

on: push

jobs:
  deno:
    name: Running Deno Tools
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Lint
        run: make lint

      - name: Test
        run: make test
  
